server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/geraldofranca/ms-atl-repositorio
          search-paths: user
          default-label: main